### PR TITLE
Upgrade base AMI to Fedora 37

### LINKED ISSUE #99: Upgrade the base AMI to Fedora 37
# 💡 Summary #

Upgrade the base AMI for this AMI to Fedora 37.

## Motivation and context ##

According to @bra1ncramp, there are some OpenSSL fixes available for Fedora 37 that are lacking in Fedora 36.

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request:
- Upgrades the base AMI to Fedora 37

As a side effect of bumping the version and rebuilding the AMI, we get the benefit of:
- Pulling in the latest version of any OS packages that are used
- Pulling in the changes from cisagov/ansible-role-cloudwatch-agent#48

## 💭 Motivation and context ##

* Resolves #99.  Fedora 37 was released on November 15, 2022.
* This AMI has not been refreshed in a while (since November).
* CDM requires the changes from cisagov/ansible-role-cloudwatch-agent#48 in order to ingest our instance logs into Splunk.

## 🧪 Testing ##

All automated tests pass.  I also built a staging AMI with these changes and verified that it functions as expected.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.
- [x] Build and test a staging AMI with these changes.

## ✅ Pre-merge checklist ##

- [x] Finalize version.

## ✅ Post-merge checklist ##

- [x] Create a release.

### CODE REVIEW

**Comment by jsf9k** [comment]
This PR is currently blocked, waiting on cisagov/skeleton-packer#195 to be approved, merged, and integrated into this repo via [Lineage](https://github.com/cisagov/action-lineage).

**Comment by jsf9k** [comment]
> This PR is currently blocked, waiting on [cisagov/skeleton-packer#195](https://github.com/cisagov/skeleton-packer/pull/195) to be approved, merged, and integrated into this repo via [Lineage](https://github.com/cisagov/action-lineage).

[cisagov/skeleton-packer#195](https://github.com/cisagov/skeleton-packer/pull/195) has been approved, merged, and integrated!

**Review by jmorrowomni — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
🎉

**Review by mcdonnnj — APPROVED** [review]
:shipit:

**Pull request merged**
