### PR TITLE
Use the new and improved hardening role created by @bra1ncramp

### LINKED ISSUE #117: Enable `nodev` for `/home` partition, if present
# 💡 Summary #

We should ensure that `nodev` is enabled for the `/home` partition of this AMI.

## Motivation and context ##

This improves security.

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull requests switches to the new [cisagov/ansible-role-hardening-2](https://github.com/cisagov/ansible-role-hardening-2) that @bra1ncramp created.

## 💭 Motivation and context ##

The new hardening role takes care of some security findings that were identified by the security team.

Resolves #117.

## 🧪 Testing ##

All automated tests pass.  I also built and deployed a new AMI with these changes for our staging COOL environment.  I was able to verify that the new AMI functions as intended.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.
- [x] Build and test a new staging AMI with these changes.

## ✅ Pre-merge checklist ##

- [x] Revert to the default branch of [cisagov/ansible-role-hardening-2](https://github.com/cisagov/ansible-role-hardening-2) once cisagov/ansible-role-hardening-2#1 is merged.
- [x] Finalize version.

## ✅ Post-merge checklist ##

- [x] Create a release.

### CODE REVIEW

**Comment by jsf9k** [comment]
- These changes uninstall `freeipa-server` and dependencies from the FreeIPA AMI for some reason I've yet to skry.
- I verified that using these changes results in a FreeIPA AMI that functions as expected _if I first reinstall `freeipa-server`_.

**Comment by jsf9k** [comment]
> * These changes uninstall `freeipa-server` and dependencies from the FreeIPA AMI for some reason I've yet to skry.

I determined and corrected the cause of this behavior.  See [this commit](https://github.com/cisagov/ansible-role-hardening-2/pull/1/commits/1e49a20be196b62ce837e06da610fa3d6b75334a).

**Comment by jsf9k** [comment]
> * These changes uninstall `freeipa-server` and dependencies from the FreeIPA AMI for some reason I've yet to skry.
> * I verified that using these changes results in a FreeIPA AMI that functions as expected _if I first reinstall `freeipa-server`_.

Update:
* ~These changes uninstall `freeipa-server` and dependencies from the FreeIPA AMI for some reason I've yet to skry.~
* I verified that using these changes results in a FreeIPA AMI that functions as expected ~_if I first reinstall `freeipa-server`_~.

**Review by dv4harr10 — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
👍 👍 🎉

**Comment by jsf9k** [comment]
After rebasing I again built a new staging AMI and verified that it functions as expected.

**Review by dav3r — APPROVED** [review]

**Review by jasonodoom — APPROVED** [review]

**Pull request merged**
